version: "3.5"

services:
  app:
    image: jeknom/portfolio-alpine:latest
    restart: unless-stopped
    container_name: portfolio-app
    depends_on:
      - db
    ports:
      - "443:3000"
    environment:
      ENVIRONMENT: production
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      DEBUG: ${DEBUG}
      SSL_CERT_DIRECTORY_PATH: ${SSL_CERT_DIRECTORY_PATH}
      SSL_CERT_KEY_FILENAME: ${SSL_CERT_KEY_FILENAME}
      SSL_CERT_FILENAME: ${SSL_CERT_FILENAME}
      SSL_CERT_BUNDLE_FILENAME: ${SSL_CERT_BUNDLE_FILENAME}
    volumes:
      - ${SSL_CERT_DIRECTORY_PATH}/${SSL_CERT_KEY_FILENAME}:/opt/portfolio/${SSL_CERT_KEY_FILENAME}
      - ${SSL_CERT_DIRECTORY_PATH}/${SSL_CERT_FILENAME}:/opt/portfolio/${SSL_CERT_FILENAME}
  db:
    image: mysql
    restart: unless-stopped
    container_name: portfolio-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./database/container:/var/lib/mysql"
      - "./database/initialization:/docker-entrypoint-initdb.d"
  adminer:
    image: adminer
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8080:8080
  nginx:
    image: nginx
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
