version: "3.5"

services:
  app:
    build: "./app"
    restart: unless-stopped
    container_name: dev-portfolio-app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      ENVIRONMENT: development
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./app:/opt/portfolio"
  db:
    image: mysql
    restart: unless-stopped
    container_name: portfolio-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - "./database/container:/var/lib/mysql"
      - "./database/initialization:/docker-entrypoint-initdb.d"
  adminer:
    image: adminer
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8080:8080
