export const ADMIN = "ADMIN";
export const ALLOWED_TO_SEE_DASHBOARD = "ALLOWED_TO_SEE_DASHBOARD";
export const ALLOWED_TO_EDIT_POSTS = "ALLOWED_TO_EDIT_POSTS";
export const ALLOWED_TO_EDIT_MEDIA = "ALLOWED_TO_EDIT_IMAGES";
export const ALLOWED_TO_EDIT_HIGHLIGHTS = "ALLOWED_TO_EDIT_HIGHLIGHTS";
export const ALLOWED_TO_EDIT_ACHIEVEMENTS = "ALLOWED_TO_EDIT_ACHIEVEMENTS";
export const ALLOWED_TO_EDIT_SKILLS = "ALLOWED_TO_EDIT_SKILLS";
export const ALLOWED_TO_EDIT_CONTACT_INFORMATION =
  "ALLOWED_TO_EDIT_CONTACT_INFORMATION";
export const ALLOWED_TO_EDIT_MAINTAINER = "ALLOWED_TO_EDIT_MAINTAINER";
export const ALLOWED_TO_EDIT_OPEN_GRAPH_DATA =
  "ALLOWED_TO_EDIT_OPEN_GRAPH_DATA";
